//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinariaEntities : DbContext
    {
        public VeterinariaEntities()
            : base("name=VeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbcirugia> tbcirugias { get; set; }
        public virtual DbSet<tbCita> tbCitas { get; set; }
        public virtual DbSet<tbDUENO> TDueno { get; set; }
        public virtual DbSet<tbEmpleado> TEmpleado { get; set; }
        public virtual DbSet<tbenfermedad> tbenfermedads { get; set; }
        public virtual DbSet<tbespecie> TEspecie { get; set; }
        public virtual DbSet<tbfamilia> TFamilia { get; set; }
        public virtual DbSet<tbmedicina> tbmedicinas { get; set; }
        public virtual DbSet<Tbpaciente> Tbpacientes { get; set; }
        public virtual DbSet<tbPuesto> TPuestos { get; set; }
        public virtual DbSet<tbraza> tbrazas { get; set; }
        public virtual DbSet<tbReceta> tbRecetas { get; set; }
        public virtual DbSet<TbTelefonoDueno> TbTelefonoDuenoes { get; set; }
        public virtual DbSet<tbTelEmpleado> tbTelEmpleadoes { get; set; }
        public virtual DbSet<tbtiporiesgc> tbtiporiesgcs { get; set; }
        public virtual DbSet<tbTurno> tbTurnoes { get; set; }
        public virtual DbSet<tbusuario> tbusuarios { get; set; }
    }
}
