//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcirugia
    {
        public int cod_cirugia { get; set; }
        public int cod_paciente { get; set; }
        public int duracion_minutos { get; set; }
        public string descripcion { get; set; }
        public string anestesia { get; set; }
        public string nombre { get; set; }
    
        public virtual Tbpaciente Tbpaciente { get; set; }
        public virtual tbtiporiesgc tbtiporiesgc { get; set; }
    }
}
