//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCita
    {
        public int cod_cita { get; set; }
        public System.DateTime fecha_cita { get; set; }
        public int hora_cita { get; set; }
        public int cod_paciente { get; set; }
        public int descrip_cita { get; set; }
        public System.DateTime fecha { get; set; }
        public int cod_medico { get; set; }
    
        public virtual tbEmpleado tbEmpleado { get; set; }
        public virtual Tbpaciente Tbpaciente { get; set; }
    }
}
