//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbespecie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbespecie()
        {
            this.Tbpacientes = new HashSet<Tbpaciente>();
            this.tbrazas = new HashSet<tbraza>();
        }
    
        public int cod_especie { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int cod_familia { get; set; }
    
        public virtual tbfamilia tbfamilia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbpaciente> Tbpacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbraza> tbrazas { get; set; }
    }
}
