//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmedicina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbmedicina()
        {
            this.tbenfermedads = new HashSet<tbenfermedad>();
            this.tbRecetas = new HashSet<tbReceta>();
        }
    
        public int cod_medicina { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int dosis { get; set; }
        public string uomdosis { get; set; }
        public int frecuencia { get; set; }
        public string uom_frecuencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbenfermedad> tbenfermedads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReceta> tbRecetas { get; set; }
    }
}
