//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbpaciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbpaciente()
        {
            this.tbcirugias = new HashSet<tbcirugia>();
            this.tbCitas = new HashSet<tbCita>();
            this.tbRecetas = new HashSet<tbReceta>();
        }
    
        public int cod_paciente { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public int cod_especie { get; set; }
        public int cod_dueno { get; set; }
        public int cod_medico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbcirugia> tbcirugias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCita> tbCitas { get; set; }
        public virtual tbDUENO tbDUENO { get; set; }
        public virtual tbEmpleado tbEmpleado { get; set; }
        public virtual tbespecie tbespecie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReceta> tbRecetas { get; set; }
    }
}
