//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbraza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbraza()
        {
            this.tbenfermedads = new HashSet<tbenfermedad>();
        }
    
        public int cod_raza { get; set; }
        public string nombre { get; set; }
        public Nullable<int> longevidad { get; set; }
        public int cod_especie { get; set; }
    
        public virtual tbespecie tbespecie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbenfermedad> tbenfermedads { get; set; }
    }
}
