//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTelEmpleado
    {
        public int cod_empleado { get; set; }
        public string telefono { get; set; }
    
        public virtual tbEmpleado tbEmpleado { get; set; }
    }
}
