//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbusuario
    {
        public Nullable<int> cod_emp { get; set; }
        public int cod_user { get; set; }
        public string nombre { get; set; }
        public string contrasena { get; set; }
    
        public virtual tbEmpleado tbEmpleado { get; set; }
    }
}
